# Generated by Django 4.2.6 on 2023-11-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuOnline', '0008_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='idCard',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
