# Generated by Django 4.2.6 on 2023-11-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuOnline', '0010_remove_bill_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
