# Generated by Django 4.2.6 on 2023-11-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuOnline', '0011_bill_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
    ]
